name: C++ Numerical CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
  actions: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install deps
      run: sudo apt update && sudo apt install -y build-essential g++
    
    - name: Debug files & Makefile
      run:
